apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud_network_service
spec:
  selector:
    matchLabels:
      app: cloud_network_service
  template:
    metadata:
      labels:
        app: cloud_network_service
    spec:
      containers:
        - name: cloud_network_service
          image: szefoka/cloud_network_service:{{ .Values.env.APP_VERSION }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
                path: /health
                port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
                path: /health
                port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3