apiVersion: apps/v1
kind: Deployment
metadata:
  name: CloudNetworkService_HF
spec:
  selector:
    matchLabels:
      app: CloudNetworkService_HF
  template:
    metadata:
      labels:
        app: CloudNetworkService_HF
    spec:
      containers:
        - name: CloudNetworkService_HF
          image: nagypalmarton/CloudNetworkService_HF:{{ .Values.env.APP_VERSION }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
                path: /health
                port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
                path: /health
                port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3