apiVersion: v1
kind: Service
metadata:
  name: cloud_network_service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cloud_network_service